package bacardi;

import java.util.List;

import org.junit.Test;

/**
 * @author gangpeng.wgp
 * @date 2019/01/17 上午11:35
 */

public class GenerateConfigCenterUtilTest {

    @Test
    public void val() throws Exception {
        System.out.println(GenerateConfigCenterCodeUtil.val("<a href=\"http://crm-m.alibaba.com \" target=\"_blank\">请点击：<font style='color:red;font-size:13px;'>马上下载销售移动工作平台APP</font></a>"));

    }

    public static String str = "[{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.RESKEY_MANUALDISTLIMIT\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\","
        + "\"keyFieldParam2\":\"RESKEY_MANUALDISTLIMIT\",\"realKeyParam2\":\"manualDistributeLimit\",\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerQueryBatchUpdateImpl.java\"],\"cacheData\":2000,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali"
        + ".caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.RESKEY_GROUPUPLIMIT\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"RESKEY_GROUPUPLIMIT\",\"realKeyParam2\":\"addToGroupLimit\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerQueryBatchUpdateImpl.java\"],\"cacheData\":2000,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\","
        + "\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.customer.service.impl.ServiceAutoDistributeAoImpl.SERVICE_DISTRIBUTE_NEW\",\"keyClassParam2\":\"com.ali.caesar.biz.customer.service.impl.ServiceAutoDistributeAoImpl\",\"keyFieldParam2\":\"SERVICE_DISTRIBUTE_NEW\",\"realKeyParam2\":\"SERVICE_DISTRIBUTE_NEW\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/service/impl/ServiceAutoDistributeAoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\","
        + "\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.customer.impl.interrelated.BatchUpdateSyncOpportunityProcessImpl.MAX_ONCE_IMPORT_NUM\",\"keyClassParam2\":\"com.ali.caesar.biz.customer.impl.interrelated.BatchUpdateSyncOpportunityProcessImpl\",\"keyFieldParam2\":\"MAX_ONCE_IMPORT_NUM\",\"realKeyParam2\":null,\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/interrelated/BatchUpdateSyncOpportunityProcessImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\","
        + "\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.customer.isearch.aop.advice.CustomerIsearchQueryInterceptor.NEW_ISEARCH_AREA\",\"keyClassParam2\":\"com.ali.caesar.biz.customer.isearch.aop.advice.CustomerIsearchQueryInterceptor\",\"keyFieldParam2\":\"NEW_ISEARCH_AREA\",\"realKeyParam2\":\"NEW_ISEARCH_AREA\",\"valueType\":\"STRING\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/isearch/aop/advice/CustomerIsearchQueryInterceptor.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"SEX\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"SEX\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,"
        + "\"realKeyParam2\":null,\"valueType\":\"MAP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/sendmail/GGSCustomerSendMailBoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\","
        + "\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"MAP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/common/src/java/com/ali/caesar/biz/common/UserHelperImpl.java\",\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/notify/OppTransferLogMessageListener.java\","
        + "\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/web/customer/action/CustomerOceanQueryPrepare.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\","
        + "\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.RESKEY_SCHEDULE_STOP_TRIGGER\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"RESKEY_SCHEDULE_STOP_TRIGGER\",\"realKeyParam2\":\"scheduleStopTrigger\",\"valueType\":\"STRING\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/common/src/java/com/ali/caesar/biz/schedule/DefaultTriggerListener.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource"
        + ".OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.web.customer.service.action.ServiceCsCaseFollowQueryAction.RES_OP_ISVALID\",\"keyClass\":\"com.ali.caesar.web.customer.service.action.ServiceCsCaseFollowQueryAction\",\"keyField\":\"RES_OP_ISVALID\",\"realKey\":\"OP_ISVALID\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"MAP\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/web/customer/service/action/ServiceCsCaseFollowQueryAction.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\","
        + "\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.activity.PromotionManageBoImpl.PROMOTION_LIMIT\",\"keyClassParam2\":\"com.ali.caesar.biz.activity.PromotionManageBoImpl\",\"keyFieldParam2\":\"PROMOTION_LIMIT\",\"realKeyParam2\":null,\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/activity/src/java/com/ali/caesar/biz/activity/PromotionManageBoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali"
        + ".b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.common.ClotConstant.APP_GEOGRAPHY_OPTION\",\"keyClass\":\"com.ali.caesar.biz.common.ClotConstant\",\"keyField\":\"APP_GEOGRAPHY_OPTION\",\"realKey\":\"APP_GEOGRAPHY_OPTION\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"LIST_OPTION_DO\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/common/src/java/com/ali/caesar/biz/common/UserHelperImpl.java\"],\"cacheData\":null,\"valid\":true,\"empty\":false,\"valueClass\":null},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"CountryList\","
        + "\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"CountryList\",\"valueType\":\"STRING\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerLeadsMailBoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz"
        + ".BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.RESKEY_OPPGRADELIMIT\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"RESKEY_OPPGRADELIMIT\",\"realKeyParam2\":\"oppGradeLimit\",\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerQueryBatchUpdateImpl"
        + ".java\"],\"cacheData\":2000,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.customer.impl.SalesCapacityBoImpl.CAESAR_Constants\",\"keyClass\":\"com.ali.caesar.biz.customer.impl.SalesCapacityBoImpl\",\"keyField\":\"CAESAR_Constants\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.customer.impl.SalesCapacityBoImpl"
        + ".STORE_CAPACITY\",\"keyClassParam2\":\"com.ali.caesar.biz.customer.impl.SalesCapacityBoImpl\",\"keyFieldParam2\":\"STORE_CAPACITY\",\"realKeyParam2\":\"storeCapacity\",\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/SalesCapacityBoImpl.java\"],\"cacheData\":200,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali"
        + ".caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.LEADS_SEND_MAIL_SUBJECT+countryCode\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"LEADS_SEND_MAIL_SUBJECT+countryCode\",\"realKeyParam2\":null,\"valueType\":\"STRING\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerLeadsMailBoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"SCENE_TYPE\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"SCENE_TYPE\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,"
        + "\"valueType\":\"LIST_RESOURCE_DO_GROUP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/martini/web/ActionUtil.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":null},{\"keyType\":\"KEY_STR\",\"keyValue\":\"CAESAR_HA3_AUTODIS\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"CAESAR_HA3_AUTODIS\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,"
        + "\"valueType\":\"MAP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/AutoDistributeAoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.CUSTOMER_ACTIVITY_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"CUSTOMER_ACTIVITY_CONSTANTS\","
        + "\"realKey\":\"CUSTOMER_ACTIVITY_CONSTANTS\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.SERVICE_CUSTOMER_ACITIVITY_ALLOW_MONTH\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"SERVICE_CUSTOMER_ACITIVITY_ALLOW_MONTH\",\"realKeyParam2\":\"serviceCustomerAcitivityAllowMonth\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/service/impl/ServiceCustomerActivityBoImpl.java\"],\"cacheData\":6,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"CAESAR_Constants\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,"
        + "\"realKeyParam2\":null,\"valueType\":\"MAP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/customer/decorator/detail/GstInfo.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\","
        + "\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.LEADS_SEND_MAIL_TO+countryCode\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"LEADS_SEND_MAIL_TO+countryCode\",\"realKeyParam2\":null,\"valueType\":\"STRING\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerLeadsMailBoImpl.java\"],\"cacheData\":null,\"valid\":false,"
        + "\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.customer.sendmail.recordinflow.BaseRecordInflowOperation.MAX_ONCE_IMPORT_NUM\",\"keyClassParam2\":\"com.ali.caesar.biz"
        + ".customer.sendmail.recordinflow.BaseRecordInflowOperation\",\"keyFieldParam2\":\"MAX_ONCE_IMPORT_NUM\",\"realKeyParam2\":null,\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/sendmail/recordinflow/BaseRecordInflowOperation.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"ISERVICE_CONFIG\","
        + "\"keyClass\":null,\"keyField\":null,\"realKey\":\"ISERVICE_CONFIG\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"MAP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CaesarBlackCustomerBoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\","
        + "\"keyValue\":\"com.ali.caesar.biz.customer.activity.impl.CacheActivityCategoryManBoImpl.CAESAR_ACT_CATEGORY_RESOURCE\",\"keyClass\":\"com.ali.caesar.biz.customer.activity.impl.CacheActivityCategoryManBoImpl\",\"keyField\":\"CAESAR_ACT_CATEGORY_RESOURCE\",\"realKey\":\"CAESAR_ACT_CATEGORY_RESOURCE\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"LIST_OPTION_DO\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/activity/impl/CacheActivityCategoryManBoImpl.java\"],\"cacheData\":[],\"valid\":false,\"empty\":true,\"valueClass\":\"com.ali.martini.common.ResourceDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.customer.batchimport.spec.ResourceLoadHelper.RESOURCE_Country\",\"keyClass\":\"com.ali.caesar.biz.customer.batchimport.spec.ResourceLoadHelper\","
        + "\"keyField\":\"RESOURCE_Country\",\"realKey\":\"CAESAR_Country\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"LIST_RESOURCE_DO\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/batchimport/spec/ResourceLoadHelper.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.martini.common.ResourceDo\"},"
        + "{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"Martini_Link\",\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"Martini_Link\",\"valueType\":\"STRING\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/customer/action/GGSCustDetailAction.java\"],\"cacheData\":\"https://crm-martini.alibaba-inc.com/martini/common/framePage.htm\",\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.CUSTOMER_ACTIVITY_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\","
        + "\"keyField\":\"CUSTOMER_ACTIVITY_CONSTANTS\",\"realKey\":\"CUSTOMER_ACTIVITY_CONSTANTS\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.SERVICE_CUSTOMER_ACITIVITY_ALLOW_DAILY\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"SERVICE_CUSTOMER_ACITIVITY_ALLOW_DAILY\",\"realKeyParam2\":\"serviceCustomerAcitivityAllowDaily\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/service/impl/ServiceCustomerActivityBoImpl.java\"],\"cacheData\":32,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.activity.salesaction.impl.CaesarOrgResourceBoImpl.KEY_RESNAME\",\"keyClass\":\"com.ali.caesar.biz.activity.salesaction.impl.CaesarOrgResourceBoImpl\","
        + "\"keyField\":\"KEY_RESNAME\",\"realKey\":\"ORG_SALES_ACTION\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"LIST_RESOURCE_DO_GROUP\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/activity/src/java/com/ali/caesar/biz/activity/salesaction/impl/CaesarOrgResourceBoImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":null},{\"keyType\":\"KEY_CLASS\","
        + "\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_SCHEDULE_SWITCH\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_SCHEDULE_SWITCH\",\"realKey\":\"caesar_schedule_switch\",\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"uic_register_receive_switch\",\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"uic_register_receive_switch\",\"valueType\":\"STRING\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/notify/GgsUicRegisterMessageListener.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"CAESAR_Constants\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"AUTO_INTERRELATED_STRATEGY\","
        + "\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"AUTO_INTERRELATED_STRATEGY\",\"valueType\":\"STRING\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/interrelated/CustomerInterrelatedCalculatorImpl.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"CAESAR_Constants\",\"keyClass\":null,"
        + "\"keyField\":null,\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"GGS_ROOT_SALES_ORG\",\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"GGS_ROOT_SALES_ORG\",\"valueType\":\"STRING\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/helper/GgsUserOrgHelper.java\",\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerAddBoImpl"
        + ".java\"],\"cacheData\":\"100013878\",\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"CAESAR_Constants\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"GGS_ROOT_SERVICE_ORG\",\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"GGS_ROOT_SERVICE_ORG\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/service/impl/ServiceMatchEmailBoImpl.java\",\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/web/customer/service/action/ServiceGroupServiceAction.java\"],\"cacheData\":100013882,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.web.customer.service.action"
        + ".ServiceGroupServiceAction.RES_APP_ORG_ITP_SERVICE_GROUP\",\"keyClass\":\"com.ali.caesar.web.customer.service.action.ServiceGroupServiceAction\",\"keyField\":\"RES_APP_ORG_ITP_SERVICE_GROUP\",\"realKey\":\"APP_ORG_ITP_SERVICE_GROUP\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"LIST_OPTION_DO\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/web/customer/service/action/ServiceGroupServiceAction.java\"],\"cacheData\":null,\"valid\":true,\"empty\":false,\"valueClass\":null},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_STR\","
        + "\"keyValueParam2\":\"sendMailLimit\",\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"sendMailLimit\",\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/web/src/java/com/ali/caesar/web/customer/activity/ActivityManagePrepare.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants"
        + ".CUSTOMER_ACTIVITY_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"CUSTOMER_ACTIVITY_CONSTANTS\",\"realKey\":\"CUSTOMER_ACTIVITY_CONSTANTS\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.SALES_CUSTOMER_ACITIVITY_ALLOW_MONTH\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"SALES_CUSTOMER_ACITIVITY_ALLOW_MONTH\",\"realKeyParam2\":\"salesCustomerAcitivityAllowMonth\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/SalesCustomerActivityBoImpl.java\"],\"cacheData\":6,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\","
        + "\"keyTypeParam2\":\"KEY_STR\",\"keyValueParam2\":\"EsbEveSendListLimit\",\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":\"EsbEveSendListLimit\",\"valueType\":\"INT\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/sendmail/SendMailUtils.java\"],\"cacheData\":null,\"valid\":false,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar"
        + ".biz.BizConstants.RESOURCE_CONSTANTS\",\"keyClass\":\"com.ali.caesar.biz.BizConstants\",\"keyField\":\"RESOURCE_CONSTANTS\",\"realKey\":\"CAESAR_Constants\",\"keyTypeParam2\":\"KEY_CLASS\",\"keyValueParam2\":\"com.ali.caesar.biz.BizConstants.RESKEY_MOVEOCEANELIMIT\",\"keyClassParam2\":\"com.ali.caesar.biz.BizConstants\",\"keyFieldParam2\":\"RESKEY_MOVEOCEANELIMIT\",\"realKeyParam2\":\"moveOceanLimit\",\"valueType\":\"INT\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/impl/CustomerQueryBatchUpdateImpl.java\"],\"cacheData\":2000,\"valid\":true,\"empty\":false,\"valueClass\":\"com.ali.b2b.crm.base.resource.OptionDo\"},{\"keyType\":\"KEY_STR\",\"keyValue\":\"CAESAR_Country\",\"keyClass\":null,\"keyField\":null,\"realKey\":\"CAESAR_Country\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,"
        + "\"realKeyParam2\":null,\"valueType\":\"MAP_RESOURCE_DO\",\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/EsbCaesarInfoProviderImpl.java\",\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/export/ReportExcelExport.java\",\"/Users/weigangpeng/IdeaProjects/caesar/biz/customer/src/java/com/ali/caesar/biz/customer/sendmail/GGSCustomerSendMailBoImpl.java\"],\"cacheData\":null,\"valid\":false,"
        + "\"empty\":false,\"valueClass\":\"com.ali.martini.common.ResourceDo\"},{\"keyType\":\"KEY_CLASS\",\"keyValue\":\"com.ali.caesar.biz.common.ClotConstant.APP_ORG_ITP_OPTION\",\"keyClass\":\"com.ali.caesar.biz.common.ClotConstant\",\"keyField\":\"APP_ORG_ITP_OPTION\",\"realKey\":\"APP_ORG_ITP_OPTION\",\"keyTypeParam2\":null,\"keyValueParam2\":null,\"keyClassParam2\":null,\"keyFieldParam2\":null,\"realKeyParam2\":null,\"valueType\":\"MAP_OPTION_DO\","
        + "\"files\":[\"/Users/weigangpeng/IdeaProjects/caesar/biz/common/src/java/com/ali/caesar/biz/common/UserHelperImpl.java\"],\"cacheData\":null,\"valid\":true,\"empty\":false,\"valueClass\":null}]\n";

    public static String str2 = "";

    @Test
    public void generateConfigCenterCode() throws Exception {

        //path = "/Users/weigangpeng/IdeaProjects/aegean_home/shixi/biz/platform/src/java/com/ali/caesar/platform/config/ConfigCenter.java";

        String path = "/Users/weigangpeng/IdeaProjects/caesar/biz/common/src/java/com/ali/common/ConfigCenter.java";

        GenerateConfigCenterCodeUtil.generateConfigCenterCode(path, str);

    }



}